#import tkinter as tk
from tkinter import *
#from math import sqrt
win = Tk()
win.geometry("1290x1225")
#win.resizeable(0,0)
win.title("Unit Conversion")
##########Starting the function############
def btn_click(item):
    global expression
    expression = expression+str(item)
    input_text.set(expression)
'''def btnSquareRoot(self):
   #result = False
   global current
   current = math.sqrt(input_text)
   input_text.set(current)'''
def bt_clear():
    global expression
    expression =""
    input_text.set("")
def bt_equal():
    global expression
    result = str(eval(expression))
    input_text.set(result)
    expression=""

expression = ""
#input frame creation... top
input_text = StringVar()
input_frame = Frame(win,width=310, height=40,bd=0,highlightbackground="red", highlightcolor="green",highlightthickness=3)
input_frame.pack(side=TOP)
#input field creation
input_field = Entry(input_frame, font=('arial', 18, 'bold'), textvariable=input_text, width=150, bg="#eee", bd=0, justify=RIGHT)
input_field.grid(row=0, column=0)
input_field.pack(ipady=1)
#Let us creating another 'Frame' for the button background
btns_frame = Frame(win, width=312, height=305, bg="gray")
btns_frame.pack()
#first row
clear = Button(btns_frame, text = "C", fg = "black", width=5, height=2,bd=0,bg="#eee",cursor="hand1",command= lambda:bt_clear()).grid(row=0,column=0,padx=1,pady=1)
mtr_to_mlmtr=Button(btns_frame, text="Meter to Mm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=0,column=1,padx=1,pady=1)
mtr_to_km = Button(btns_frame, text="Meter to Km", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=0,column=2,padx=1,pady=1)
mtr_feet=Button(btns_frame, text="Meter to Feet", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*3.281")).grid(row=0,column=3,padx=1,pady=1)
mtr_to_miles=Button(btns_frame,text="Meter to Miles", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1609")).grid(row=0,column=4,padx=1,pady=1)
mtr_to_inch=Button(btns_frame, text="Meter to Inch", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*39.37")).grid(row=0,column=5,padx=1,pady=1)
mtr_to_sf = Button(btns_frame, text="Meter to SqrFeet", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10.764")).grid(row=0,column=6,padx=1,pady=1)
mtr_cm=Button(btns_frame, text="Meter to CM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=0,column=7,padx=1,pady=1)
km_to_miles=Button(btns_frame,text="KM to Miles", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1.609")).grid(row=0,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Hectare to SqureMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=0,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Hectare to SqureDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=0,column=10,padx=1,pady=1)
plus=Button(btns_frame,text="+",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("+")).grid(row=0,column=11,padx=1,pady=1)
#second row
one=Button(btns_frame, text="1", fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand1",command=lambda:btn_click(1)).grid(row=1,column=0,padx=1,pady=1)
km_to_meter=Button(btns_frame, text="KM to Meter", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=1,column=1,padx=1,pady=1)
km_to_gram = Button(btns_frame, text="Kg to Gram", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=1,column=2,padx=1,pady=1)
km_pnds=Button(btns_frame, text="Kg to Pounds", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*2.205")).grid(row=1,column=3,padx=1,pady=1)
km_to_ltr=Button(btns_frame,text="Kg to Litter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1")).grid(row=1,column=4,padx=1,pady=1)
gram_to_mltr=Button(btns_frame, text="Gram to mltr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1")).grid(row=1,column=5,padx=1,pady=1)
gram_to_pnds= Button(btns_frame, text="Gram to pound", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/454")).grid(row=1,column=6,padx=1,pady=1)
mls_to_km=Button(btns_frame, text="Miles to KM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1.609")).grid(row=1,column=7,padx=1,pady=1)
miles_to_yards=Button(btns_frame,text="Miles to Yards", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1760")).grid(row=1,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Hectare to SqureMM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=1,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Hectare to Area", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=1,column=10,padx=1,pady=1)
minus=Button(btns_frame,text="-",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("-")).grid(row=1,column=11,padx=1,pady=1)
#third row
two=Button(btns_frame, text="2",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand1",command=lambda:btn_click(2)).grid(row=2,column=0,padx=1,pady=1)
mils_to_feet=Button(btns_frame, text="Miles to feet", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*5280")).grid(row=2,column=1,padx=1,pady=1)
ltr_to_kg = Button(btns_frame, text="Liter to Kg", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1")).grid(row=2,column=2,padx=1,pady=1)
ltr_to_mltr=Button(btns_frame, text="Liter to Mltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=2,column=3,padx=1,pady=1)
mltr_to_ltr=Button(btns_frame,text="Mililiter to Liter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=2,column=4,padx=1,pady=1)
mtr_to_gram=Button(btns_frame, text="Mltr to Gram", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1")).grid(row=2,column=5,padx=1,pady=1)
circule = Button(btns_frame, text="AreaOfCircule", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=2,column=6,padx=1,pady=1)
square=Button(btns_frame, text="AreaOfSquare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("**2")).grid(row=2,column=7,padx=1,pady=1)
age=Button(btns_frame,text="AgeCalculate", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("-2021")).grid(row=2,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="HctoLtr to Ltr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=2,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="HctoLtr to CubeDm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=2,column=10,padx=1,pady=1)
minus=Button(btns_frame,text="*",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*")).grid(row=2,column=11,padx=1,pady=1)
#fourth row
three=Button(btns_frame,text="3",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand1",command=lambda:btn_click(3)).grid(row=3,column=0,padx=1,pady=1)
decimtr_to_mtr=Button(btns_frame, text="Mtr to Decimtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10")).grid(row=3,column=1,padx=1,pady=1)
lyt_to_mtr= Button(btns_frame, text="Mtr to LightYear", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.461e+15")).grid(row=3,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Mtr to CM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=3,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Mtr to MicroMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=3,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Mtr to Parsec", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*3.086e+16")).grid(row=3,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Mtr to NanoMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+9")).grid(row=3,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqrtMtr to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=3,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqrtMtr to SqrtCm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("1e+6")).grid(row=3,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="HctoLtr to CubeCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=3,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="HctoLtr to CubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=3,column=10,padx=1,pady=1)
mutiplay=Button(btns_frame,text="/",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/")).grid(row=3,column=11,padx=1,pady=1)
#fifth row
four=Button(btns_frame,text="4",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand1",command=lambda:btn_click(4)).grid(row=4,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqrtCm to Hectare", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+8")).grid(row=4,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Area to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=4,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqrtKm to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=4,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqrtMM to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("1e+10")).grid(row=4,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Cels to Faharn", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9/5+32")).grid(row=4,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Reaumur to Cels", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/0.80000")).grid(row=4,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Faharen to Kelvin", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("-32*5/9+270.15")).grid(row=4,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Kelvin to Cels", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("-273.15")).grid(row=4,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeMtr to DeciLtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=4,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeMtr to CentiLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=4,column=10,padx=1,pady=1)
mutiplay=Button(btns_frame,text="%",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("%2")).grid(row=4,column=11,padx=1,pady=1)
#sixth row
five=Button(btns_frame,text="5",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(5)).grid(row=5,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubicMtr to CubCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000")).grid(row=5,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Centiliter to Ltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=5,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubMM to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=5,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Hectoltr to Decltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=5,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="LytYear to Decimtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.461e+16")).grid(row=5,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="LytYear to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.223e+18")).grid(row=5,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="LytYear to KM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.461e+12")).grid(row=5,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="LytYear to CM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.461e+17")).grid(row=5,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeMtr to CubeMM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000000")).grid(row=5,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeMtr to CubeMltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000")).grid(row=5,column=10,padx=1,pady=1)
mutiplay=Button(btns_frame,text="0",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("0")).grid(row=5,column=11,padx=1,pady=1)
#seventh row
six=Button(btns_frame,text="6",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(6)).grid(row=6,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="LytYear to McroMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.4607e+21")).grid(row=6,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="LytYear to NanoMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*9.4607e+24")).grid(row=6,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Km to LytYear", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/9.461e+12")).grid(row=6,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Km to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000")).grid(row=6,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="KM to Mtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=6,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="KM to Mcromtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000000")).grid(row=6,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="KM to NamoMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000000000000")).grid(row=6,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="KM to Decimtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=6,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeCM to DeciLtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=6,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeCM to CentiLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10")).grid(row=6,column=10,padx=1,pady=1)
dot=Button(btns_frame,text=".",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(".")).grid(row=6,column=11,padx=1,pady=1)
#8th row
seven=Button(btns_frame,text="7",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(7)).grid(row=7,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Decimtr to lytYear", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/9.461e+16")).grid(row=7,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Decimrt to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=7,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Decimtr to KM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=7,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Decimeter to CM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10")).grid(row=7,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Cm to LytYear", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/9.461e+17")).grid(row=7,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Cm to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10")).grid(row=7,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Cm to Km", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100000")).grid(row=7,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Cm to Mtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=7,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Km to Cm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100000")).grid(row=7,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CM to DeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10")).grid(row=7,column=10,padx=1,pady=1)
expo=Button(btns_frame,text="**",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("**")).grid(row=7,column=11,padx=1,pady=1)
#9th row
eigth=Button(btns_frame,text="8",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(8)).grid(row=8,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Cm to Mcromtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=8,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Decimtr to McroM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100000")).grid(row=8,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CM to NanoMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000000")).grid(row=8,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="McroMtr to DeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100000")).grid(row=8,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="McroMtr to LytYear", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/9.223e+18")).grid(row=8,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="McroMtr to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=8,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="McroMtr to KM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+9")).grid(row=8,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="McroMtr to Cm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=8,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="McroMtr to Mtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=8,column=9,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="McroMtr to NanoMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000")).grid(row=8,column=10,padx=1,pady=1)
floor=Button(btns_frame,text="//",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("//")).grid(row=8,column=11,padx=1,pady=1)
#10th row
nine=Button(btns_frame,text="9",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(9)).grid(row=9,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="NanoMtr to DeciMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+8")).grid(row=9,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="NanoMtr LytYear", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/9.223e+18")).grid(row=9,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="NanoMtr to MM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=9,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="NanoMtr to KM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+12")).grid(row=9,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="NanoMtr to CM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+7")).grid(row=9,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="NanoMtr to Mtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+9")).grid(row=9,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="NanoMtr to McroMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=9,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqurDeciMtr to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=9,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureCm to Hectare", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+8")).grid(row=9,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="SqureKm to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=9,column=10,padx=1,pady=1)
floor=Button(btns_frame,text="00",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("00")).grid(row=9,column=11,padx=1,pady=1)
#11th row
ten=Button(btns_frame, text="10",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=10,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureMM to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+10")).grid(row=10,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CentiLtr to CubeDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=10,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CentiLtr to Ltr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=10,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="SqureDecimtr to SqureMtr ", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=10,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureDecimtr to SqureCM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=10,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqureDecimtr to SqureKm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+8")).grid(row=10,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureDecimtr to SqureMM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=10,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CentiLtr to CubeMM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=10,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureDecimtr to Area", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=10,column=9,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqureDecimtr to Hectare", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=10,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "=", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:bt_equal()).grid(row=10,column=11,padx=1,pady=1)
#12th row
ten=Button(btns_frame, text="11",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=11,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureCm to SqureMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100000")).grid(row=11,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="SqureCm to SqureDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=11,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureCm to SqureKm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+10")).grid(row=11,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqureCm to SqureMM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=11,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureCm to Area", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=11,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CentiLtr to Mltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10")).grid(row=11,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureKm to SqureMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000")).grid(row=11,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqureKm to SqureDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1e+8")).grid(row=11,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureKm to SqureCM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1e+10")).grid(row=11,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="SqureKm to SqureMM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1e+12")).grid(row=11,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "Sqrt", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=11,column=11,padx=1,pady=1)
#13th row
ten=Button(btns_frame, text="12",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=12,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureKm to Area", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=12,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeDeciMtr to HectoLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=12,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureMM to SqureMtr", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+6")).grid(row=12,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="SqureMM to SqureDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=12,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="SqureMM to SqureCM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100")).grid(row=12,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="SqureMM to SqureKm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1e+12")).grid(row=12,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="SqureMM to Area", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=12,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeDeciMtr to CubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=12,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Are to SqureMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100")).grid(row=12,column=9,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Are to SqureDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10000")).grid(row=12,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "000", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("000")).grid(row=12,column=11,padx=1,pady=1)
#15thth row
ten=Button(btns_frame, text="14",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=13,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Are to SqureCM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1000000")).grid(row=13,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Are to SqureKm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=13,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Area to SqureMM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*1e+8")).grid(row=13,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeDeciMtr to DeciLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10")).grid(row=13,column=4,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="DeciLtr to CubeMM", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*100000")).grid(row=13,column=5,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeMM to Mltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/1000")).grid(row=13,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CentiLtr to HectoLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10000")).grid(row=13,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CentiLtr to CubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/100000")).grid(row=13,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CentiLtr to CubeCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("*10")).grid(row=13,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CentiLtr to DeciLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("/10")).grid(row=13,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "0000", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("0000")).grid(row=13,column=11,padx=1,pady=1)
#16th ro
ten=Button(btns_frame, text="15",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=14,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Hectare to SqureCM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Hectare to SqureKM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="HctoLtr to Mltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="HctoLtr to CubeMM", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="HctoLtr to CentiLiter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="HctoLtr to DeciLiter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Mltr to CubeCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Mltr to DeciLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Mltr to CentiLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=9,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Mltr to Ltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=14,column=11,padx=1,pady=1)
#17thth row
ten=Button(btns_frame, text="16",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=15,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeMtr to HectoLiter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeMtr to CubeCm", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=2,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeMtr to DeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=3,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeMtr to Ltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeCM to HectoLiter", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeCM to CubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeCM to CubeDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeCM to Ltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=8,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="DeciLtr to CubeCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=9,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="DeciLtr to Centiltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=15,column=11,padx=1,pady=1)
#18thth row
ten=Button(btns_frame, text="17",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=16,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Ltr to HectoLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Ltr to CubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Ltr to CubeCm", fg="black", width=16, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Ltr to DeciLtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Ltr to Centiltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Ltr to CubeDeciMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=6,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="Mltr to Hectoltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=7,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="Mltr to cubeMtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="DeciLtr to CubeDecimtr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=9,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeMM to Centiltr", fg="black",width=16,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=16,column=11,padx=1,pady=1)
'''#19thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=17,column=0,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CentiLtr to CubeDeciMtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=1,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CentiLtr to Ltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CentiLtr to CubeMM", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CentiLtr to Mltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeDeciMtr to HectoLtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeDeciMtr to CubeMtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeDeciMtr to CubeCm", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeDeciMtr to DeciLtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=8,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeDeciMtr to CentiLtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=9,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=17,column=10,padx=1,pady=1)
#20thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=18,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeDeciMtr to CubeMM", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=1,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeDeciMtr to Mtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=2,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="Ltr to CubeMM", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=3,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="Ltr to Mltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=4,padx=1,pady=1)
cm_to_mtr=Button(btns_frame, text="CubeMM to Hectoltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=5,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeMM to CubeMtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=6,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeMM to CubeCm", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=7,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeMM to Deciltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=8,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=10,padx=1,pady=1)'''
'''#21thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=20,column=0,padx=1,pady=1)
parsec_to_mtr=Button(btns_frame, text="CubeMM to Ltr", fg="black", width=14, height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=19,column=9,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="DeciLtr to Ltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=38,column=10,padx=1,pady=1)
nano_to_mtr= Button(btns_frame, text="CubeMM to Mltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=19,column=10,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeMM to DeciMtr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=19,column=10,padx=1,pady=1)
micromtr_to_mtr=Button(btns_frame,text="CubeDeciMtr to Ltr", fg="black",width=14,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click("")).grid(row=18,column=10,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=20,column=6,padx=1,pady=1)
#22thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=21,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=21,column=11,padx=1,pady=1)
#23thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=22,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=22,column=11,padx=1,pady=1)
#24thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=23,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=23,column=6,padx=1,pady=1)
#25thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=24,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=24,column=6,padx=1,pady=1)
#26thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=25,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=25,column=6,padx=1,pady=1)
#27thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=26,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=26,column=6,padx=1,pady=1)
#28thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=27,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=27,column=6,padx=1,pady=1)
#29thth row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=28,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=28,column=6,padx=1,pady=1)
#30th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=29,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=29,column=6,padx=1,pady=1)
#31th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=30,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=30,column=6,padx=1,pady=1)
#32th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=31,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=31,column=6,padx=1,pady=1)
#33th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=32,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=32,column=6,padx=1,pady=1)
#34th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=33,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=33,column=6,padx=1,pady=1)
#35th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=34,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=34,column=6,padx=1,pady=1)
#36th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=35,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=35,column=6,padx=1,pady=1)
#37th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=36,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=36,column=6,padx=1,pady=1)
#38th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=37,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=37,column=6,padx=1,pady=1)
#39th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=38,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=38,column=6,padx=1,pady=1)
#40th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=39,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=39,column=6,padx=1,pady=1)
#41th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=40,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=40,column=6,padx=1,pady=1)
#42th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=41,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=41,column=6,padx=1,pady=1)
#43th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=42,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=42,column=6,padx=1,pady=1)
#44th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=43,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=43,column=6,padx=1,pady=1)
#44th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=44,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=44,column=6,padx=1,pady=1)
#45th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=45,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=45,column=6,padx=1,pady=1)
#46th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=46,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=46,column=6,padx=1,pady=1)
#47th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=47,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=47,column=6,padx=1,pady=1)
#48th row
ten=Button(btns_frame, text="13",fg="black",width=5,height=2,bd=0,bg="#eee",cursor="hand2",command=lambda:btn_click(10)).grid(row=48,column=0,padx=1,pady=1)
equal = Button(btns_frame, text = "", fg="black", width=5, height=2, bd=0, bg="#eee", cursor="hand2",command=lambda:btn_click("")).grid(row=48,column=6,padx=1,pady=1)'''
